#!/bin/bash
USERNAME='INSERT_USERNAME'
DBUSER='INSERT_DB_USER'
DBNAME='INSERT_DB_NAME'
DBPASSWORD='INSERT_DB_PASSWORD'
PROJECTNAME='INSERT_PROJECT_NAME'
DJANGO_APP_NAME='INSERT_DJANGO_APP_NAME'
VENV_NAME='INSERT_VENV_NAME'
